### PR TITLE
Fixed gitignore | Boyan Vidolov

### PR DESCRIPTION
**Pull request by boyan1742**
Boyan Vidolov
SI 1 1MI0600250
Added new lines in gitignore file to ignore the IDE folders.

### CODE REVIEW

**Comment by Justsvetoslavov** [comment]
@boyan1742 Should we address the .gitignore ?

**Comment by boyan1742** [comment]
> @boyan1742 Should we address the .gitignore ?

Yes, I have closed the PR because I broke the branches and other files were included. 

I think, it would be a good thing to ignore IDE specific folders in order to make working in this repo easier.

**Comment by Justsvetoslavov** [comment]
Do you feel like adding a PR for IDE specific folders in the .gitignore? (at least for VS/VS code/Clion)

Otherwise, I will address them later today.

**Comment by boyan1742** [comment]
I will make the PR right now.

**Pull request closed without merging**
